# Generated by Django 6.0.5 on 2026-05-15 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=20)),
                ('icon', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('specific_objective', models.CharField(max_length=10)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10)),
                ('order', models.PositiveIntegerField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='curriculum.module')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_index', models.PositiveSmallIntegerField()),
                ('narrative', models.TextField()),
                ('initial_state', models.JSONField()),
                ('target_state', models.JSONField()),
                ('min_commands', models.PositiveIntegerField()),
                ('hard_cap', models.PositiveIntegerField()),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='curriculum.scenario')),
            ],
            options={
                'ordering': ['template_index'],
                'unique_together': {('scenario', 'template_index')},
            },
        ),
    ]
